### ISSUE TITLE
Make issue

### ISSUE THREAD

**Issue by gpeyton** [raysalemi/python4uvm_examples#11]
First off, thanks for the great contributions on pyuvm! I recently purchased Ray's book on Python for RTL verification and am enjoying going through it. 

I'm getting set up with pyuvm on Mac, and hitting a make problem. In `27_uvm_test_testbench_3.0`, I `make` and get the error below. 

I confirm that the simple `my_object = uvm_object("my_object")` test works fine. I can open a python terminal and import cocotb and pyuvm. Also, I have cototb version `1.8.0.dev0` installed, and pyuvm `2.9.0`. 

Many thanks for the assistance. 

<img width="1571" alt="Screenshot 2023-04-18 at 3 48 07 PM" src="https://user-images.githubusercontent.com/1481988/232889241-bc431b60-85f5-4a21-8c15-b07f23ee9cf8.png">

**Comment by raysalemi** [comment]
This is a bug I hope to fix this week. pyuvm does not handle the “dev” in
the cocotb version string properly.

Can you go to a release version of cocotb?

**Comment by gpeyton** [comment]
Sure, I can reinstall version 1.7.2? 

EDIT: Just checked and that works.

**Comment by raysalemi** [comment]
That should work.
